---
- name: Set up Nginx Webserver
  hosts: "{{dynamic_hosts}}"
  gather_facts: true
  remote_user: adminuser
  become: true
  connection: ssh
  pre_tasks: []
  vars:
    dynamic_hosts: role_slave_webservers
    enable_firewall: false
    packages:
      - curl ## Not required for Nginx
      - vim ## Not required for Nginx
      - git ## Not required for Nginx
      - ufw
      - nginx
    files:
      - ./files/index.html
      - ./files/github-mark.png

  tasks:
    - name: Update apt and install required system packages
      apt:
        pkg:
          - "{{ item }}"
        state: latest
        update_cache: true ## equivalent of "apt-get update"
      loop: "{{ packages }}"

    - name: UFW - Allow SSH connections
      community.general.ufw:
        rule: allow
        name: OpenSSH ## Allow SSH connections through FW
      when:
        - ansible_distribution == "Ubuntu"
        - enable_firewall | bool

    - name: UFW - Allow Nginx Http connections
      community.general.ufw:
        rule: allow
        name: Nginx HTTP ## Use 'Nginx HTTPS' if Nginx is configurred to listen on HTTPS
      when:
        - ansible_distribution == "Ubuntu"
        - enable_firewall | bool

    - name: UFW - Enable and deny by default
      community.general.ufw:
        state: enabled
        default: deny
      when:
        - ansible_distribution == "Ubuntu"
        - enable_firewall | bool

    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: true

    - name: Use custom webpage
      copy:
        src: "{{ item }}"
        dest: /var/www/html/
        mode: "0755"
      loop: "{{ files }}"
      notify:
        - Restart nginx

  handlers:
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
