---
# tasks file for nginx-webserver

- name: Update apt and install required system packages
  ansible.builtin.apt:
    package:
      - "{{ item }}"
    state: latest
    update_cache: true ## equivalent of "apt-get update"
  loop: "{{ packages }}"

- name: Enable Nginx Traffic(Port 80) in OS firrwall if requested
  ansible.builtin.include_tasks:
    file: ufw.yaml
    apply:
      tags:
        - ufw
  tags: [firewall, ufw]
  when: enable_firewall | bool

- name: Start Nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Copy Github Logo
  ansible.builtin.copy:
    src: github-mark.png
    dest: /var/www/html/
    mode: "0755"

- name: Copy Custom HTML site
  ansible.builtin.template:
    src: index.j2
    dest: /var/www/html/index.html
    mode: "0755"
  notify:
    - Restart nginx
