- name: Test Ubuntu VM Setup
  hosts: ubuntu-vm
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install NGINX
      apt:
        name: nginx
        state: present

    - name: Start and enable NGINX
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Verify NGINX installation
      shell: curl http://localhost
      register: nginx_status

    - name: Display NGINX status
      debug:
        msg: "{{ nginx_status.stdout }}"
