---
plugin: azure_rm

include_vm_resource_groups:
  - ansible-vm-resources

auth_source: auto
conditional_groups:
  # since this will be true for every host, every host sourced from this inventory plugin config will be in the
  # group 'all_the_hosts'
  all_the_hosts: true

# places hosts in dynamically-created groups based on a variable value.
keyed_groups:
  # places each host in a group named 'tag_(tag name)_(tag value)' for each tag on a VM.
  # - prefix: tag
  #   key: tags
  # places each host in a group named 'azure_loc_(location name)', depending on the VM's location
  - prefix: azure_loc
    key: location
  # places host in a group named 'some_tag_X' using the value of the 'sometag' tag on a VM as X, and defaulting to the
  # value 'none' (eg, the group 'some_tag_none') if the 'sometag' tag is not defined for a VM.
  - prefix: role
    key: tags.role | default('none')
