---
- name: Set up Nginx Webserver on Ubuntu machine
  gather_facts: true
  remote_user: adminuser
  hosts: "{{ dynamic_hosts }}"
  become: true
  connection: ssh
  pre_tasks: []
  vars:
    dynamic_hosts: role_slave_webservers

  roles:
    - role: azure_vm_ufw
      when: enable_firewall | bool
    - role: nginx_webserver
