---
- name: Set up Nginx Webserver on Ubuntu machine
  gather_facts: true
  remote_user: adminuser
  hosts: "{{ dynamic_hosts }}"
  become: true
  connection: ssh
  pre_tasks: []
  vars:
    dynamic_hosts: role_slave_webservers

  roles:
    - azure-vms-ufw
    - nginx-webserver
